Ch1 console games
code-for-tomorrow/python pull request #143
Opened 2021-07-22 03:40 UTC by PavithraY22

## Location

Specify chapters and sections here.

- Chapter(s): 1
- Section(s): Console games

## Changes

- Created 3 new games for ch1

## Notes

- Add any notes here for the Curriculum Development team

**Add all relevant labels to this PR (e.g. if it's about a practice problem, add the practice problem label)**

2021-07-23 00:43 UTC, chrehall68 commented on guessthepassword.py
> +pas = str("password")
you don't actually need the str() since "password" is already a string

2021-07-23 00:53 UTC, chrehall68 commented on TowerOfCourage.py
> +# Story + Directions: This Summer, an amusement
Not exactly a game.

2021-07-23 01:04 UTC, chrehall68 requested changes
It mostly looks good. Keep in mind that, since students will have finished our intermediate course that already deals with functions and classes, you can make the problems a bit harder. I recommend that you try to come up with another example to replace TowerofCourage.py

2021-07-27 19:05 UTC, PavithraY22 commented
> It mostly looks good. Keep in mind that, since students will have finished our intermediate course that already deals with functions and classes, you can make the problems a bit harder. I recommend that you try to come up with another example to replace TowerofCourage.py

I am not too familiar with classes however I can incorporate them in game if you let me know how to create a certain game with classes. I created another game with functions called "Hangman" so please look into that.

2021-07-28 11:48 UTC, chrehall68 approved these changes
LGTM now.

2021-07-28 21:05 UTC, BenVN123 approved these changes
Looks good.

2021-07-29 12:00 UTC, merged