Create the example for drawing and moving
code-for-tomorrow/python pull request #162
Opened 2022-05-28 16:06 UTC by chrehall68

This creates the full example for Ch. 2.3 in the pygame course.

2022-05-29 01:12 UTC, hpanchal092 requested changes

2022-05-29 01:12 UTC, hpanchal092 commented on games/chapter2/examples/draw_objects.py
> +    # this is equivalent to green_rectangle = green_rectangle.move(1, 2)
i ran a quick test, `move_ip()` is not the same as `move()`. the `move()` method moves the rectangle to the specific coordinate, and the `move_ip()` will move the rectangle relative to where it already is. we should change this comment as well as edit the notion to fix that

2022-05-29 01:13 UTC, hpanchal092 commented on games/chapter2/examples/draw_objects.py
> +    # this is equivalent to green_rectangle = green_rectangle.move(1, 2)
everything else lgtm 👍

2022-05-30 19:49 UTC, hpanchal092 commented on games/chapter2/examples/draw_objects.py
> +    # this is equivalent to green_rectangle = green_rectangle.move(1, 2)
nvm im a huge dumbass just realized the second example is equating to itself

2022-05-30 19:49 UTC, hpanchal092 approved these changes
LGTM!

2022-06-04 22:28 UTC, Aadya-Jain approved these changes
LGTM!

2022-06-05 00:44 UTC, merged