Add Ch. 12 problem
code-for-tomorrow/python pull request #40
Opened 2020-08-03 03:42 UTC by neha-peddinti

Food Class
Ch. 12
Inheritance

2020-08-04 21:27 UTC, phrdang commented
@neha-peddinti please ignore the flake8 saying that the list slicing is wrong. flake8 is wrong, there's a bug in rule E203 that's being fixed.

**Rules**
flake8 Rule E203: https://github.com/PyCQA/pycodestyle/issues/373
Black slicing rules: https://black.readthedocs.io/en/stable/the_black_code_style.html#slices

**flake8 GitHub**
Issue: https://github.com/PyCQA/pycodestyle/issues/373
PR: https://github.com/PyCQA/pycodestyle/pull/914

2020-08-04 21:42 UTC, abhatia1205 requested changes
This is a great problem! Only a few tweaks are required. First of all, when you call ```Food.__init__(self, *args)```, the ```self``` keyword is not supposed to be passed. Also, it is better coding practice to use the ```super()``` function instead of the name of the actual class, ```Food```. This being said, if the students aren't yet supposed to have learned about the ```super``` function, I totally get that too. 

Nice work!

2020-08-04 21:44 UTC, abhatia1205 requested changes

2020-08-04 21:44 UTC, abhatia1205 commented on 2_intermediate/chapter12/solutions/food_class.py
> +        Food.__init__(self, name, cals, protein, fat)
```suggestion
        super().__init__(name, cals, protein, fat)
```

2020-08-04 21:44 UTC, abhatia1205 commented on 2_intermediate/chapter12/solutions/food_class.py
> +        Food.__init__(self, name, cals, protein, fat)
```suggestion
        super().__init__(name, cals, protein, fat)
```

2020-08-04 21:44 UTC, abhatia1205 commented on 2_intermediate/chapter12/solutions/food_class.py
> +cals = protein = fat = sugar = sodium = 0
```suggestion
cals, protein, fat, sugar, sodium = 0,0,0,0,0
```

2020-08-05 00:35 UTC, srikar-eranky approved these changes
Looks good to me!

2020-11-09 05:20 UTC, merged