Update img_avg.py/ There were typos
code-for-tomorrow/python pull request #41
Opened 2020-08-03 03:43 UTC by Citrus716

Fixing Typos

**img_avg**
* Chapter # 10
* Practice

Repeat the Problem Title, Chapter #, and Section Name format for as many problems as you have.

Optional: Brief description of changes or any other notes you want to leave to the Curriculum Development team

2020-08-04 20:53 UTC, phrdang requested changes
My overall comments:
- This is a really cool problem! The main issue I see right now is the complexity - students need to understand exactly what the problem is asking and when I was reading the instructions I didn't know how to begin approaching it
- Also, this problem requires some basic knowledge of the libraries used, and I think we either need to teach students that in the main curriculum, provide a link to an article or something that they could use, or simplify this problem so that it's doable

Also please see my comment about the `solution1` function.

2020-08-04 20:53 UTC, phrdang commented on 2_intermediate/chapter10/solutions/img_avg.py
>  def solution1():
@Citrus716 could you change this to not be a function since the students haven't learned them yet?

2020-08-04 20:57 UTC, phrdang requested changes

2020-08-04 20:57 UTC, phrdang commented on 1_beginner/chapter5/practice/alternating.py
> +Alternating
@code-for-tomorrow/python who submitted this practice problem? I'm wondering because I noticed there's no solution for it...

2020-08-04 21:05 UTC, merged

2020-08-06 21:39 UTC, Citrus716 commented
> My overall comments:
> 
> * This is a really cool problem! The main issue I see right now is the complexity - students need to understand exactly what the problem is asking and when I was reading the instructions I didn't know how to begin approaching it
> * Also, this problem requires some basic knowledge of the libraries used, and I think we either need to teach students that in the main curriculum, provide a link to an article or something that they could use, or simplify this problem so that it's doable
> 
> Also please see my comment about the `solution1` function.

Yes, I didn't make the img_avg, but I see can see trouble understanding the problem. What the problem is asking for is not too hard imo as the complexities dealing with the libraries are already implemented for the student. I think maybe describing what the code does, but not expecting them to actually write the code dealing with the libraries.

Also, thanks to who wrote this problem.